---
- name: Download from S3 to control node
  amazon.aws.s3_object:
    access_key: "{{ lookup('env', 'STG_AWS_ACCESS_KEY') }}"
    secret_key: "{{ lookup('env', 'STG_AWS_SECRET_KEY') }}"
    bucket: "{{ s3_bucket }}"
    object: "{{ service_name }}/{{ service_name }}-{{ build_number }}.zip"
    dest: "~/artifact/{{ service_name }}-{{ build_number }}.zip"
    mode: get
  delegate_to: localhost

- name: Create directory on managed nodes
  become: yes
  file:
    state: directory
    path: "/opt/{{ service_name }}/"

- name: Copy zip to managed nodes
  become: yes
  copy:
    src: "~/artifact/{{ service_name }}-{{ build_number }}.zip"
    dest: "/opt/{{ service_name }}/{{ service_name }}.zip"

- name: Remove file in control node
  file:
    path: "~/artifact/{{ service_name }}-{{ build_number }}.zip"
    state: absent
  delegate_to: localhost

- name: Stop service
  become: yes
  systemd:
    name: "{{ service_name }}"
    state: stopped

- name: Unarchive artifact
  become: yes
  ansible.builtin.unarchive:
    src: "/opt/{{ service_name }}/{{ service_name }}.zip"
    dest: "/opt/{{ service_name }}/"
    remote_src: yes

- name: Update mode main
  become: yes
  ansible.builtin.file:
    path: "/opt/{{ service_name }}/main"
    mode: 'a+x'

- name: Update mode start.sh
  become: yes
  ansible.builtin.file:
    path: "/opt/{{ service_name }}/{{ service_name }}.sh"
    mode: 'a+x'

- name: Start service
  become: yes
  systemd:
    name: "{{ service_name }}"
    state: started
