all:
  vars:
  children:
    app_service:
      children:
        sample_service:
          hosts:
            sample_service_01:
              ansible_host: 127.0.0.1
              service_name: 'sample_service'
              host_name: 'sample_service_01'
              service_port: 80
              s3_bucket: 'my-s3-bucket'