all:
  vars:
  children:
    redis_server:
      children:
        redis:
          hosts:
            redis_01:
              ansible_host: 127.0.0.1
              redis_port: 6379
              redis_base_dir: '/opt/redis/redis-3.2.9'

        redis_tls:
          hosts:
            redis_tls_01:
              ansible_host: 127.0.0.1
              redis_port: 6380
              redis_base_dir: '/opt/redis/redis-6.2.11'
  