---
- name: Create redis directory in opt
  become: yes
  file:
    state: directory
    path: "/opt/redis/"

- name: Set vm.overcommit_memory to 1
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    insertafter: EOF
    line: "vm.overcommit_memory = 1"

- name: Reboot the machine after configure overcommit_memory
  become: yes
  ansible.builtin.reboot:

- name: Disable Transparent Huge Pages
  become: yes
  command: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

- name: Download redis
  become: yes
  command: "wget -qO /opt/redis/redis-4.0.9.tar.gz https://download.redis.io/releases/redis-4.0.9.tar.gz"

- name: Extract tar file
  become: yes
  command: "tar -zxvf /opt/redis/redis-4.0.9.tar.gz -C /opt/redis"

- name: Run make distclean
  become: yes
  make:
    chdir: /opt/redis/redis-4.0.9
    target: distclean

- name: Run make
  become: yes
  make:
    target: install
    chdir: /opt/redis/redis-4.0.9

- name: Update redis.conf
  become: yes
  template:
    src: redis.conf
    dest: "/opt/redis/redis-4.0.9/redis.conf"

- name: Create redis service file
  become: yes
  template:
    src: redis.service
    dest: "/etc/systemd/system/redis.service"

- name: Reload redis systemctl
  become: yes
  command: "systemctl daemon-reload"

- name: Enable redis service
  become: yes
  command: "systemctl enable redis"

- name: Start redis service
  become: yes
  command: "systemctl start redis"
