---
- name: Update nginx.conf  
  become: yes
  template:
    src: nginx.main.conf
    dest: "/etc/nginx/nginx.conf"    

- name: Validate nginx.conf
  become: yes
  command: "nginx -t"

- name: Reload nginx
  become: yes
  command: "systemctl reload nginx"

- name: Restart nginx service
  become: yes
  command: "systemctl restart nginx"
