---
- name: Install nginx
  become: yes
  ansible.builtin.apt:
    name: nginx

- name: Update nginx.conf
  become: yes
  template:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"

- name: Enable nginx service
  become: yes
  command: "systemctl enable nginx"

- name: Start nginx service
  become: yes
  command: "systemctl start nginx"
