# run command : ansible-playbook -i inventory/production|staging? playbooks/add-nginx-vhost-443.yml --extra-vars "@staging-subdomain-vhost.json"
- hosts: "{{ target }}"
  roles:
    - add-nginx-vhost-80