# run command : ansible-playbook -i inventory/production|staging? playbooks/deploy-go-service.yml --extra-vars "target=what build_number=1"
- hosts: "{{ target }}"
  roles:
    - deploy-java-service
  serial: 1