# run command : ansible-playbook -i inventory/redis.yml playbooks/install-redis-tls.yml --extra-vars "target=local"
- hosts: "{{ target }}"
  roles:
    - install-basic-sotware
    - install-redis-tls