# run command : ansible-playbook -i inventory/production|staging? playbooks/install-nginx-private.yml --extra-vars "target=what"
- hosts: "{{ target }}"
  roles:
    - install-basic-requirement
    - install-nginx
    - update-nginx-conf-main
