# run command : ansible-playbook -i inventory/production|staging?.yml playbooks/install-redis-tls.yml --extra-vars "target=what"
- hosts: "{{ target }}"
  roles:
    - install-basic-requirement
    - install-redis-tls