# run command : ansible-playbook -i inventory/production|staging?.yml playbooks/setup-go-server.yml --extra-vars "target=what major_version=14|15|16|etc"
- hosts: "{{ target }}"
  roles:
    - install-basic-requirement
    - setup-systemd
    - update-logrotate
    - install-papertrail
    - install-nodejs